// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

mod collection;
pub use self::collection::CollectionExt;
pub use self::collection::{Collection, NONE_COLLECTION};

mod item;
pub use self::item::ItemExt;
pub use self::item::{Item, NONE_ITEM};

mod prompt;
pub use self::prompt::PromptExt;
pub use self::prompt::{Prompt, NONE_PROMPT};

mod retrievable;
pub use self::retrievable::RetrievableExt;
pub use self::retrievable::{Retrievable, NONE_RETRIEVABLE};

mod service;
pub use self::service::ServiceExt;
pub use self::service::{Service, NONE_SERVICE};

mod schema;
pub use self::schema::Schema;

mod schema_attribute;
pub use self::schema_attribute::SchemaAttribute;

mod value;
pub use self::value::Value;

mod enums;
pub use self::enums::Error;
pub use self::enums::SchemaAttributeType;
pub use self::enums::SchemaType;

mod flags;
pub use self::flags::CollectionCreateFlags;
pub use self::flags::CollectionFlags;
pub use self::flags::ItemCreateFlags;
pub use self::flags::ItemFlags;
pub use self::flags::SchemaFlags;
pub use self::flags::SearchFlags;
pub use self::flags::ServiceFlags;

pub mod functions;

mod constants;
pub use self::constants::BACKEND_EXTENSION_POINT_NAME;
pub use self::constants::COLLECTION_DEFAULT;
pub use self::constants::COLLECTION_SESSION;

#[doc(hidden)]
pub mod traits {
    pub use super::CollectionExt;
    pub use super::ItemExt;
    pub use super::PromptExt;
    pub use super::RetrievableExt;
    pub use super::ServiceExt;
}
